name: "Automatic PR comment: Try this PR!"

on:
  pull_request_target:
    types: [opened]

jobs:
  write-comment:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: nefrob/pr-description@v1.1.2
        with:
            content: |
              
              ## Try this Pull Request!
              Open Julia and type:
              \`\`\`jl
              julia> import Pkg
              julia> Pkg.activate(temp=true)
              julia> Pkg.add(url="${context.payload.pull_request.head.repo.html_url}", rev="${context.payload.pull_request.head.ref}")
              julia> using ${context.payload.repository.name.replace(/\.jl$/,"")}
              \`\`\`
            regex: "jkhsdkjhasdfkjhawkejfbawkehfkajshdfkjahsdf"
            token: ${{ secrets.GITHUB_TOKEN }}
